### ISSUE TITLE
CrashLoopBackOff nginx-ingress unable to start Ingress controller 

### ISSUE THREAD

**Issue by LeducH** [nginxinc/kubernetes-ingress#1526]
**Describe the bug**
I am unable to start the nginx-ingress controller 

**To Reproduce**
1. follow the instruction [here](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/)

**Expected behavior**
nginx-ingress controller starts 

**Your environment**
* Version of the Ingress Controller - `v1.11.1]`

* Version of Kubernetes
```
% kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
* Kubernetes platform : rasberrt pi ` http://apt.kubernetes.io/ kubernetes-xenial main`

* Using NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

```
% kubectl get pods --all-namespaces -o wide
NAMESPACE       NAME                                 READY   STATUS             RESTARTS   AGE   IP               NODE         NOMINATED NODE   READINESS GATES
default         my-nginx-7cf6c4949c-m8j5t            1/1     Running            1          25h   10.40.0.0        node1-pi4    <none>           <none>
kube-system     coredns-558bd4d5db-8j2hn             1/1     Running            7          32h   10.32.0.2        master-pi4   <none>           <none>
kube-system     coredns-558bd4d5db-pxx9k             1/1     Running            7          32h   10.32.0.3        master-pi4   <none>           <none>
kube-system     etcd-master-pi4                      1/1     Running            14         32h   192.168.178.37   master-pi4   <none>           <none>
kube-system     kube-apiserver-master-pi4            1/1     Running            14         32h   192.168.178.37   master-pi4   <none>           <none>
kube-system     kube-controller-manager-master-pi4   1/1     Running            13         32h   192.168.178.37   master-pi4   <none>           <none>
kube-system     kube-proxy-7jxxl                     1/1     Running            2          32h   192.168.178.36   node1-pi4    <none>           <none>
kube-system     kube-proxy-c7htp                     1/1     Running            2          32h   192.168.178.35   node2-pi3    <none>           <none>
kube-system     kube-proxy-s92t2                     1/1     Running            14         32h   192.168.178.37   master-pi4   <none>           <none>
kube-system     kube-scheduler-master-pi4            1/1     Running            13         32h   192.168.178.37   master-pi4   <none>           <none>
kube-system     weave-net-9gtqz                      2/2     Running            16         26h   192.168.178.37   master-pi4   <none>           <none>
kube-system     weave-net-r69z7                      2/2     Running            4          26h   192.168.178.35   node2-pi3    <none>           <none>
kube-system     weave-net-xqwz6                      2/2     Running            4          26h   192.168.178.36   node1-pi4    <none>           <none>
nginx-ingress   nginx-ingress-5497bdccb5-phlsk       0/1     CrashLoopBackOff   21         87m   10.40.0.2        node1-pi4    <none>           <none>
```

```
% kubectl describe pods --namespace=nginx-ingress
Name:         nginx-ingress-5497bdccb5-phlsk
Namespace:    nginx-ingress
Priority:     0
Node:         node1-pi4/192.168.178.36
Start Time:   Sun, 11 Apr 2021 18:18:17 +0200
Labels:       app=nginx-ingress
              pod-template-hash=5497bdccb5
Annotations:  <none>
Status:       Running
IP:           10.40.0.2
IPs:
  IP:           10.40.0.2
Controlled By:  ReplicaSet/nginx-ingress-5497bdccb5
Containers:
  nginx-ingress:
    Container ID:  docker://33241cf45934f62553dd90f4d3325bfe6e57fe2ad7b3cf224a4d6f718893bef0
    Image:         nginx/nginx-ingress:1.11.1
    Image ID:      docker-pullable://nginx/nginx-ingress@sha256:eb5b4fd73325450e16d0a161d899940f9d5ea8fdbdb2bb992110d032ca59c940
    Ports:         80/TCP, 443/TCP, 8081/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
      -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 11 Apr 2021 19:51:19 +0200
      Finished:     Sun, 11 Apr 2021 19:51:19 +0200
    Ready:          False
    Restart Count:  23
    Readiness:      http-get http://:readiness-port/nginx-ready delay=0s timeout=1s period=1s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  nginx-ingress (v1:metadata.namespace)
      POD_NAME:       nginx-ingress-5497bdccb5-phlsk (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8wnrl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-8wnrl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  95m                  default-scheduler  Successfully assigned nginx-ingress/nginx-ingress-5497bdccb5-phlsk to node1-pi4
  Normal   Pulling    95m                  kubelet            Pulling image "nginx/nginx-ingress:1.11.1"
  Normal   Pulled     95m                  kubelet            Successfully pulled image "nginx/nginx-ingress:1.11.1" in 23.067481607s
  Normal   Started    94m (x4 over 95m)    kubelet            Started container nginx-ingress
  Normal   Pulled     93m (x4 over 95m)    kubelet            Container image "nginx/nginx-ingress:1.11.1" already present on machine
  Normal   Created    93m (x5 over 95m)    kubelet            Created container nginx-ingress
  Warning  BackOff    22s (x459 over 95m)  kubelet            Back-off restarting failed container
```

```
% neofetch 
  `.::///+:/-.        --///+//-:``    pi@master-pi4 
 `+oooooooooooo:   `+oooooooooooo:    ------------- 
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l 
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 4 Model B Rev 1.2 
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.10.17-v7l+ 
     `:++ooo/.        :+ooo+/.`       Uptime: 19 mins 
        ...`  `.----.` ``..           Packages: 1054 (dpkg) 
     .::::-``:::::::::.`-:::-`        Shell: zsh 5.7.1 
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/0 
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2711 (4) @ 1.500GHz 
       .::::::::`  -::::::::` `       Memory: 581MiB / 3876MiB 
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-                           
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`
```

[full log](https://pastebin.com/5F3kFQvF)

```
%  kubectl logs nginx-ingress-controller-57f4b84b5-ldkk5 -n nginx-ingress -v10
I0411 20:22:38.312976   23952 loader.go:372] Config loaded from file:  /home/pi/.kube/config
I0411 20:22:38.316383   23952 cached_discovery.go:114] returning cached discovery info from /home/pi/.kube/cache/discovery/192.168.178.37_6443/servergroups.json
I0411 20:22:38.317764   23952 cached_discovery.go:71] returning cached discovery info from /home/pi/.kube/cache/discovery/192.168.178.37_6443/apiregistration.k8s.io/v1beta1/serverresources.json
I0411 20:22:38.318216   23952 cached_discovery.go:71] returning cached discovery info from /home/pi/.kube/cache/discovery/192.168.178.37_6443/events.k8s.io/v1beta1/serverresources.json

I0411 20:22:38.330009   23952 round_trippers.go:435] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.21.0 (linux/arm) kubernetes/cb303e6" 'https://192.168.178.37:6443/api/v1/namespaces/nginx-ingress/pods/nginx-ingress-controller-57f4b84b5-ldkk5'
I0411 20:22:38.397561   23952 round_trippers.go:454] GET https://192.168.178.37:6443/api/v1/namespaces/nginx-ingress/pods/nginx-ingress-controller-57f4b84b5-ldkk5 404 Not Found in 67 milliseconds
I0411 20:22:38.397991   23952 round_trippers.go:460] Response Headers:
I0411 20:22:38.398146   23952 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 25ad5dcf-f661-47a4-a95b-2087ec4301fb
I0411 20:22:38.398299   23952 round_trippers.go:463]     Content-Length: 248
I0411 20:22:38.398564   23952 round_trippers.go:463]     Date: Sun, 11 Apr 2021 18:22:38 GMT
I0411 20:22:38.398763   23952 round_trippers.go:463]     Cache-Control: no-cache, private
I0411 20:22:38.398938   23952 round_trippers.go:463]     Content-Type: application/json
I0411 20:22:38.399106   23952 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: d0d1156f-52a3-4392-be05-50089edd99cd
I0411 20:22:38.399391   23952 request.go:1123] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"nginx-ingress-controller-57f4b84b5-ldkk5\" not found","reason":"NotFound","details":{"name":"nginx-ingress-controller-57f4b84b5-ldkk5","kind":"pods"},"code":404}
I0411 20:22:38.401379   23952 round_trippers.go:435] curl -k -v -XGET  -H "User-Agent: kubectl/v1.21.0 (linux/arm) kubernetes/cb303e6" -H "Accept: application/json, */*" 'https://192.168.178.37:6443/api/v1/namespaces/nginx-ingress'
I0411 20:22:38.408047   23952 round_trippers.go:454] GET https://192.168.178.37:6443/api/v1/namespaces/nginx-ingress 200 OK in 6 milliseconds
I0411 20:22:38.408332   23952 round_trippers.go:460] Response Headers:
I0411 20:22:38.408501   23952 round_trippers.go:463]     Cache-Control: no-cache, private
I0411 20:22:38.408637   23952 round_trippers.go:463]     Content-Type: application/json
I0411 20:22:38.408688   23952 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: d0d1156f-52a3-4392-be05-50089edd99cd
I0411 20:22:38.408824   23952 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 25ad5dcf-f661-47a4-a95b-2087ec4301fb
I0411 20:22:38.408874   23952 round_trippers.go:463]     Content-Length: 806
I0411 20:22:38.408922   23952 round_trippers.go:463]     Date: Sun, 11 Apr 2021 18:22:38 GMT
I0411 20:22:38.409089   23952 request.go:1123] Response Body: {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"nginx-ingress","uid":"42a3752e-594d-44d2-b2ed-6dd814d9d4b2","resourceVersion":"153860","creationTimestamp":"2021-04-11T16:16:43Z","labels":{"kubernetes.io/metadata.name":"nginx-ingress"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-ingress\"}}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2021-04-11T16:16:43Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:kubernetes.io/metadata.name":{}}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
I0411 20:22:38.409789   23952 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "pods \"nginx-ingress-controller-57f4b84b5-ldkk5\" not found",
  "reason": "NotFound",
  "details": {
    "name": "nginx-ingress-controller-57f4b84b5-ldkk5",
    "kind": "pods"
  },
  "code": 404
}]
F0411 20:22:38.410676   23952 helpers.go:115] Error from server (NotFound): pods "nginx-ingress-controller-57f4b84b5-ldkk5" not found
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x2574301, 0x0, 0x86, 0xfa)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1021 +0x94
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2563080, 0x3, 0x0, 0x0, 0x498bc20, 0x1cc8f67, 0xa, 0x73, 0xfda800)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:970 +0x110
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2563080, 0x3, 0x0, 0x0, 0x0, 0x0, 0x2, 0x4724148, 0x1, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x120
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1495
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0x48d4c00, 0x57, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x1dc
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1797188, 0x48b9b80, 0x1633168)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x6e0
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs.NewCmdLogs.func1(0x46d34a0, 0x49847a0, 0x1, 0x4)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go:156 +0x74
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0x46d34a0, 0x4984780, 0x4, 0x4, 0x46d34a0, 0x4984780)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x1f4
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x44d31e0, 0x44ba030, 0x44ba000, 0x6)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x274
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1e8

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2563080)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1164 +0x70
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:418 +0x100

goroutine 21 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x16330f8, 0x1797368, 0x4850000, 0x1, 0x46854c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0xf0
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x16330f8, 0x2a05f200, 0x1, 0x0, 0x0, 0x1, 0x46854c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x80
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x16330f8, 0x2a05f200, 0x1, 0x46854c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x48
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x80

goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0xa6cc8070, 0x72, 0xffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x48b9734, 0x72, 0x800, 0x8de, 0xffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x48b9720, 0x48aa900, 0x8de, 0x8de, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1a4
net.(*netFD).Read(0x48b9720, 0x48aa900, 0x8de, 0x8de, 0x48aa905, 0x1633b70, 0x8d9)
	/usr/local/go/src/net/fd_posix.go:55 +0x38
net.(*conn).Read(0x4674cd0, 0x48aa900, 0x8de, 0x8de, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x64
crypto/tls.(*atLeastReader).Read(0x4c506f0, 0x48aa900, 0x8de, 0x8de, 0x10, 0x4c506f0, 0x488e000)
	/usr/local/go/src/crypto/tls/conn.go:776 +0x78
bytes.(*Buffer).ReadFrom(0x450a76c, 0x1796544, 0x4c506f0, 0x345, 0x205174, 0x1361848, 0x14dee78)
	/usr/local/go/src/bytes/buffer.go:204 +0xa4
crypto/tls.(*Conn).readFromUntil(0x450a600, 0x17981f0, 0x4674cd0, 0x5, 0x4674cd0, 0x32f)
	/usr/local/go/src/crypto/tls/conn.go:798 +0xc4
crypto/tls.(*Conn).readRecordOrCCS(0x450a600, 0x0, 0x0, 0x4c506d0)
	/usr/local/go/src/crypto/tls/conn.go:605 +0xfc
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0x450a600, 0x4c44000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1276 +0x154
bufio.(*Reader).Read(0x4c30720, 0x48cc8a0, 0x9, 0x9, 0x0, 0x0, 0x1)
	/usr/local/go/src/bufio/bufio.go:227 +0x22c
io.ReadAtLeast(0x1796418, 0x4c30720, 0x48cc8a0, 0x9, 0x9, 0x9, 0x1633900, 0x4a09c8, 0x1633901)
	/usr/local/go/src/io/io.go:328 +0x6c
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0x48cc8a0, 0x9, 0x9, 0x1796418, 0x4c30720, 0x0, 0x0, 0x0, 0x48c0fd4, 0x4c2a580)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x54
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0x48cc880, 0x4c541b0, 0x0, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0x74
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0x48c0fd4, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1819 +0xdc
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0x44380f0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1741 +0x60
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:705 +0x580
```

**Comment by soneillf5** [comment]
Hi LeducH,

Thanks for submitting this issue. 

I took a look at the logs but couldn't find anything obviously incorrect. To figure out the cause of the issue would require more investigation.

Unfortunately, we don't support kubernetes version 1.21 yet. In addition, we also don't support ARM based CPUs, such as the Raspberry Pi.

As we don't support this use case, we won't be investigating the issue further.
