### ISSUE TITLE
Controller pods fail with resources without TLS, but with enabled cert-manager integration

### ISSUE THREAD

**Issue by 0m1xa** [nginxinc/kubernetes-ingress#2717]
**Describe the bug**
The ingress controller fails when I create a `VirtualServer `resource without `TLS `section but with cert-manager integration enabled.

**To Reproduce**
1. Enable cert-manager integration with values.yaml
```
controller:
  enableCertManager: true
  enableSnippets: true
rbac:
  create: true
replicaCount: 1

```
2. Add self-signed issuer
3. Deploy VirtualServer without TLS. I wanted to test plan
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: <vs-name>
  namespace: <namespace>
spec:
  host: <host>
  routes:
  - action:
      pass: app
    path: /
  upstreams:
  - name: app
    port: 80
    service: service-name
```
4. See pod(s) in ingress namespace in the `CrashLoopBackOff` state

```
I0524 13:10:09.150496       1 main.go:213] Starting NGINX Ingress Controller Version=2.2.1 GitCommit=9d1331a520f82918db5d8018dd926aaf557c4a93 Date=2022-05-18T22:58:12Z Arch=linux/amd64 PlusFlag=false
I0524 13:10:09.158400       1 main.go:344] Kubernetes version: 1.21.9
I0524 13:10:09.165718       1 main.go:456] Using nginx version: nginx/1.21.6
2022/05/24 13:10:09 [notice] 12#12: using the "epoll" event method
2022/05/24 13:10:09 [notice] 12#12: nginx/1.21.6
2022/05/24 13:10:09 [notice] 12#12: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2022/05/24 13:10:09 [notice] 12#12: OS: Linux 5.4.188-104.359.amzn2.x86_64
2022/05/24 13:10:09 [notice] 12#12: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/05/24 13:10:09 [notice] 12#12: start worker processes
2022/05/24 13:10:09 [notice] 12#12: start worker process 14
2022/05/24 13:10:09 [notice] 12#12: start worker process 15
I0524 13:10:09.204964       1 listener.go:54] Starting Prometheus listener on: :9113/metrics
I0524 13:10:09.208478       1 cm_controller.go:184] Starting cert-manager control loop
I0524 13:10:09.208649       1 shared_informer.go:240] Waiting for caches to sync for vs-cm-shim
I0524 13:10:09.208784       1 leaderelection.go:248] attempting to acquire leader lease nginx-ingress/nginx-ingress-nginx-ingress-leader-election...
I0524 13:10:09.306878       1 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"3ds", Name:"ing1", UID:"5b349e6b-671d-4fe3-883a-37c7e9f59ad4", APIVersion:"networking.k8s.io/v1", ResourceVersion:"3572013", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Configuration for 3ds/ing1 was added or updated 
I0524 13:10:09.307940       1 event.go:285] Event(v1.ObjectReference{Kind:"VirtualServer", Namespace:"3ds", Name:"testvs", UID:"8065d17b-9af3-444a-b781-fca64f2f4dbb", APIVersion:"k8s.nginx.org/v1", ResourceVersion:"3569333", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Configuration for 3ds/testvs was added or updated 
I0524 13:10:09.308336       1 event.go:285] Event(v1.ObjectReference{Kind:"VirtualServer", Namespace:"3ds", Name:"testvs2", UID:"ff967b55-8b56-4b9e-a909-eccbf4a49424", APIVersion:"k8s.nginx.org/v1", ResourceVersion:"3574372", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Configuration for 3ds/testvs2 was added or updated 
I0524 13:10:09.308463       1 event.go:285] Event(v1.ObjectReference{Kind:"Policy", Namespace:"3ds", Name:"ingress-mtls-policy", UID:"3bc6223c-3c55-4bb5-b352-bceeaa0c6ff8", APIVersion:"k8s.nginx.org/v1", ResourceVersion:"2531051", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Policy 3ds/ingress-mtls-policy was added or updated
I0524 13:10:09.309649       1 shared_informer.go:247] Caches are synced for vs-cm-shim 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17f7b70]

goroutine 855 [running]:
github.com/nginxinc/kubernetes-ingress/internal/certmanager.issuerForVirtualServer(0xc0002df2c0?)
	/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/certmanager/sync.go:269 +0x30
github.com/nginxinc/kubernetes-ingress/internal/certmanager.SyncFnFor.func1({0x20035d8, 0xc0004a1d80}, 0xc0003a4200)
	/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/certmanager/sync.go:67 +0x91
github.com/nginxinc/kubernetes-ingress/internal/certmanager.(*CmController).processItem(0xc00050d2c0, {0x20035d8, 0xc0004a1d80}, {0xc000320f80, 0xb})
	/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/certmanager/cm_controller.go:110 +0x1ac
github.com/nginxinc/kubernetes-ingress/internal/certmanager.(*CmController).runWorker.func1(0xc00050d2c0, {0x199aaa0?, 0xc00022fbc0?}, 0x1267a00?, {0x20035d8?, 0xc0004a1d80?})
	/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/certmanager/cm_controller.go:224 +0x129
github.com/nginxinc/kubernetes-ingress/internal/certmanager.(*CmController).runWorker(0xc00050d2c0, {0x20035d8, 0xc0004a1d80})
	/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/certmanager/cm_controller.go:232 +0x7e
created by github.com/nginxinc/kubernetes-ingress/internal/certmanager.(*CmController).Run
	/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/certmanager/cm_controller.go:197 +0x41a

```
**Expected behavior**
A virtualserver was created without any problem and handles HTTP connections. 

**Your environment**
nginx version: `nginx/1.21.6`
nginx ingress controller version: `NGINX Ingress Controller Version=2.2.1 GitCommit=9d1331a520f82918db5d8018dd926aaf557c4a93 Date=2022-05-18T22:58:12Z Arch=linux/amd64 PlusFlag=false`
nginx ingress-controller helm chart version: `0.13.1`
nginx ingress-controller helm App version: `2.2.1`
kubernetes: `v1.21.5-eks-9017834`

**Comment by brianehlert** [comment]
> A virtualserver was created without any problem and handles HTTP connections.
Why would you not expect a configuration error?

The settings are conflicting and the software cannot predict the intent.  
The safe approach would be to report an error and not apply any configuration.  
Thus requiring the misconfiguration to be corrected in order to not improperly expose any endpoint.

**Comment by jasonwilliams14** [comment]
@0m1xa Not sure I understand what you are trying to accomplish.
You want to enable/use cert-manager, but you want Ingress to only handle HTTP requests and not HTTPS? 
If that is the case, why the need to enable cert-manager if you have no intent to handle HTTPS requests at the Ingress tier?

Do I understand your use case correctly?

**Comment by 0m1xa** [comment]
By the way, I've tested `VirtualServer` with `tls` enabled but `cert-manager` section was disabled.
And you know what? 
It fails in this configuration too.
